[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
extra_scripts = pre:scripts/patch_lvgl_cyd.py
monitor_speed = 115200
upload_port = COM7
upload_speed = 921600
monitor_port = COM7
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
  bblanchon/ArduinoJson@^7.4.2
  https://github.com/ropg/LVGL_CYD.git#1.2.2
build_flags =
  -D LV_CONF_SKIP=1
  -D LV_USE_TFT_ESPI=1
  -D LV_FONT_MONTSERRAT_14=1
  -D LV_FONT_MONTSERRAT_18=1
  -D LV_FONT_MONTSERRAT_10=1
  -D LV_FONT_MONTSERRAT_12=1
  -D LV_FONT_MONTSERRAT_28=1
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=21
  -D TFT_BACKLIGHT_ON=HIGH
  -D USE_HSPI_PORT=1
  -D SPI_FREQUENCY=40000000
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SMOOTH_FONT=1
